spring:
  application:
    name: fixtime-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:fixtime}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: ${SERVER_PORT:8080}
